### ISSUE TITLE
Font symbols are not displayed

### ISSUE THREAD

**Issue by MCF** [littlevgl/pc_simulator_sdl_visual_studio#3]
The LV_SYMBOL_ defined font "characters" are currently not displaying.  They worked in the 5.3 supporting version of this simulator but do not currently work with the 6.0 supporting version.

**Comment by kisvegabor** [comment]
I'll investigate it soon. Thank you for the feedback!

**Comment by kisvegabor** [comment]
@MCF 
I've found the issue and fixed it in the `master` branch.
Could you test it if you have time?

**Comment by MCF** [comment]
Problem was in lvgl, fixed by updating to the latest version of lvgl in d6596b932217c94de17743cc6376c6aaf985d1b9

**Comment by kisvegabor** [comment]
Awesome! Thank you very much!
